#!/usr/bin/env python
from xdg.Menu import parse, Menu, MenuEntry
from xdg.DesktopEntry import DesktopEntry
import os, stat, errno, sys

#execs = []

def create_dir_menu(menu, dest_dir):
    for submenu in menu.Entries:
        if isinstance(submenu, Menu):
            create_dir_menu(submenu, dest_dir)
        elif isinstance(submenu, MenuEntry):
            for parent in submenu.Parents:
                pdir = parent.getPath()
                filename =  os.path.join(dest_dir, pdir,
                                         submenu.DesktopEntry.getName() )
                create_script(filename, submenu.DesktopEntry.getExec())
#               execs.append(submenu.DesktopEntry.getExec())

def create_script(filename, content):
    try:
        os.makedirs(os.path.dirname(filename))
    except OSError as e:
        if e.errno is not errno.EEXIST:
            raise

    content = content.replace('${SHELL:-bash}', '')

    with open(filename, 'w') as f:
        f.write(content)

    st = os.stat(filename)
    os.chmod(filename, st.st_mode | stat.S_IEXEC)

# Main

usage = """Create a directory structure in a given path based on the Kali
aplications menu in Kali Linux. This is useful when you want to browse
the Kali menu inside a terminal or when you use a WM that is not fully
XDG compatible.

Usage:

    menu2dir -d <path>
"""
if len(sys.argv) > 2:
    if sys.argv[1] == '-d':
        kalimenu = parse('/etc/xdg/menus/applications-merged/kali-applications.menu')
        dest_dir = os.path.abspath(sys.argv[2])

        create_dir_menu(kalimenu, dest_dir)
    else:
        print usage
else:
    print usage
